services:
  react:
    container_name: bugtracker-front
    build: react-app
    ports:
      - 8084:80

    networks:
      - bugtracker-network

  api:
    container_name: bugtracker-api
    build:
      context: .

    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/bugtracker"
      SPRING_DATASOURCE_USERNAME: bugtracker
      SPRING_DATASOURCE_PASSWORD: bugtracker
      SPRING_LOGGING_LEVEL_ROOT: INFO
      SPRING_SERVER_PORT: 8083
    networks:
      - bugtracker-network
    ports:
      - 8083:8083

  postgres:
    container_name: bugtracker-postgres
    image: postgres:13-alpine
    restart: always
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_USER: bugtracker
      POSTGRES_PASSWORD: bugtracker
      POSTGRES_DB: bugtracker
    ports:
      - 5434:5432
      
    networks:
      bugtracker-network:
networks:
  bugtracker-network:
