properties([parameters([
        booleanParam(defaultValue: true, name: 'rebuildContainer'),
])])


pipeline {
    agent any

    stages {
        stage("GIT") {
            steps {
                sh "ssh joza@87.90.82.189 'cd bugtracker && git pull --rebase'"
            }
        }
        stage("DOCKER COMPOSE") {
            steps {
                script {
                    if (params.rebuildContainer) {
                        sh "ssh joza@87.90.82.189 'cd bugtracker/bug-tracker-joza && docker-compose up --build -d'"
                    } else {
                        sh "ssh joza@87.90.82.189 'cd bugtracker/bug-tracker-joza && docker-compose up -d'"
                    }
                }
            }
        }
    }
}
